# Generated by Django 2.2.12 on 2020-05-31 10:54

from django.db import migrations


class Migration(migrations.Migration):
    """
    Finalizes the migration to the new UserPresence model.
    We can get rid of the old table together with its data,
    and replace it with the new one.
    """

    dependencies = [
        ('zerver', '0282_userpresencenew_fill_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPresence',
        ),
        migrations.RenameModel(
            old_name='UserPresenceNew',
            new_name='UserPresence',
        ),
    ]
