# Generated by Django 3.2.12 on 2022-03-05 14:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0377_message_edit_history_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
