# Generated by Django 5.2.6 on 2025-10-06 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0751_externalauthid_zerver_user_externalauth_uniq"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBuddyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(related_name="buddy_lists", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
